#cloud-config

write_files:
  - path: /run/udev/rules.d/79-netname.rules
    permissions: 444
    content: |
      SUBSYSTEM!="net", GOTO="netname_end"
      ACTION!="add", GOTO="netname_end"
      ATTR{address}=="00:00:00:00:00:00", GOTO="netname_end"

      IMPORT{program}="/usr/share/oem/bin/netname.sh $kernel"

      NAME=="", ENV{ID_NET_NAME_SIMPLE}!="", NAME="$env{ID_NET_NAME_SIMPLE}"

      LABEL="netname_end"

coreos:
    units:
      - name: user-configdrive.service.d/netconf.conf
        runtime: yes
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/coreos-cloudinit --from-configdrive=/media/configdrive --convert-netconf=debian
      - name: ping-out.service
        runtime: yes
        enable: yes
        content: |
          [Unit]
          After=user-config.target

          [Install]
          WantedBy=user-config.target

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/usr/bin/sh -c "ping -A -c1 $(ip route | awk '/default/ { print $3 }')"
      - name: rename-network-interfaces.service
        command: start
        runtime: yes
        content: |
          [Unit]
          Before=user-config.target

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/systemctl stop systemd-networkd
          ExecStart=/usr/bin/ip link set ens3 down
          ExecStart=/usr/bin/udevadm trigger --subsystem-match=net --action=add
          ExecStart=/usr/bin/systemctl start systemd-networkd
      - name: media-configdrive.mount
        command: start
        runtime: yes
        content: |
          [Unit]
          DefaultDependencies=no
          Conflicts=umount.target
          Before=user-config.target umount.target

          [Mount]
          What=/dev/disk/by-label/config-2
          Where=/media/configdrive
          Options=ro
    oem:
      id: teeth
      name: Rackspace Teeth
      home-url: http://www.rackspace.com/
      bug-report-url: https://github.com/coreos/bugs/issues
