#cloud-config

coreos:
    units:
      - name: user-configdrive.service.d/netconf.conf
        runtime: yes
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/coreos-cloudinit --from-configdrive=/media/configdrive --convert-netconf=debian
      - name: ping-out.service
        runtime: yes
        enable: yes
        content: |
          [Unit]
          After=user-config.target

          [Install]
          WantedBy=user-config.target

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/usr/bin/sh -c "ping -A -c1 $(ip route | awk '/default/ { print $3 }')"
      - name: 00-default.link
        runtime: yes
      - name: media-configdrive.mount
        command: start
        runtime: yes
        content: |
          [Unit]
          DefaultDependencies=no
          Conflicts=umount.target
          Before=user-config.target umount.target

          [Mount]
          What=/dev/disk/by-label/config-2
          Where=/media/configdrive
          Options=ro
    oem:
      id: teeth
      name: Rackspace Teeth
      home-url: http://www.rackspace.com/
      bug-report-url: https://github.com/coreos/bugs/issues
