#cloud-config

coreos:
    units:
      - name: user-configdrive.service
        mask: yes
      - name: user-configvirtfs.service
        mask: yes
      - name: oem-cloudinit.service
        command: restart
        runtime: yes
        content: |
          [Unit]
          Description=Cloudinit from EC2-style metadata
          Requires=coreos-setup-environment.service
          After=coreos-setup-environment.service

          [Service]
          Type=oneshot
          EnvironmentFile=/etc/environment
          ExecStart=/usr/bin/coreos-cloudinit --from-configdrive=/media/configdrive --from-metadata-service
    oem:
      id: @@OEM_ID@@
      name: @@OEM_NAME@@
      home-url: @@OEM_HOME_URL@@
      bug-report-url: https://github.com/coreos/bugs/issues
write_files:
    - path: /run/systemd/system/etcd.service.d/10-oem.conf
      permissions: 0644
      content: |
        [Service]
        Environment=ETCD_PEER_ELECTION_TIMEOUT=1200
